server:
  port: 2021
spring:
  application:
    name: cz_blog_system
  datasource:
    url: jdbc:mysql://47.94.195.238 :3306/blog_system_database?characterEncoding=utf-8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
  jpa:
    show-sql: true
  redis:
    port: 6379
    password: 123456
    host: 47.94.195.238
blog.images.save-path: D:\Code\WEBProject\images


