server:
  port: 2022
spring:
  application:
    name: cz_blog_system
  datasource:
    url: jdbc:mysql://47.94.195.238 :3306/blog_system_database?characterEncoding=utf-8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
  jpa:
    show-sql: true
  redis:
    port: 6379
    password: 123456
    host: 47.94.195.238
  data:
    solr:
      host: http://47.94.195.238:8983/solr/sob_blog_core
blog.images.save-path: user/app/upload
#2MB
blog.images.max-size: 2,097,152
#控制swagger ui 是否可见
blog.swagger.config.enable: false

